### ISSUE TITLE
question about how to invoke the broadcast method of echoServer.py

### ISSUE THREAD

**Issue by jordonyang** [Nikasa1889/FaceDetectionStream#3]
Would U please tell me the code that you invoke the **broadcast** method of **echoServer.py** ? I am trying to save the recognized face image and send its url to the frnotend using autobahn,but I just do not know how to use **broadcast** method in the face recognition module.Would overwriting the protocol in echoServer.py works?

**Comment by Nikasa1889** [comment]
Hi @jordonyang, the echoServer.py script is an independent web service that echoes any message sent to it to all of its registered clients. It's called first in the script [runVideoDetection.sh](https://github.com/Nikasa1889/FaceDetectionStream/blob/973e1c314c1cc31ad75a8ba955f751afddbf4800/runVideoDetection.sh#L6). The FaceWall service then registers to the echo service [here](https://github.com/Nikasa1889/FaceDetectionStream/blob/973e1c314c1cc31ad75a8ba955f751afddbf4800/FaceWall.py#L64).

Another service that register  and listen to this echo service is a Single Page App written in React but has been coverted to plain javascript.

**Comment by jordonyang** [comment]
Thanks a lot! It halps!
